config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'pages#index'
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :nickname, :age, presence: true
	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :userparam
         has_many :posts
         validates :nickname, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
    validates :age, length: { in: 18..65 }
end

app/models/userparam.rb
class Userparam < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
  	before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
  end
  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	end
  	else
      render 'new'
  	end
  	def new
  		@post = Post.new
  		else
      render 'new'
  	end
  	end
  	def show
  	end
  	def edit
  	end
  	def update
  		@post.update(post_params)
     if @post.save
     	redirect_to root_path(@post.id)
     end
  	end
  	def destroy
  		@post.destroy
    redirect_to root_path
  	end
  	def find_post
  	@post = Post.find_by(id: params[:id])
  end
  	private
  	def post_params
  		params.require(:post).permit(:nickname, :age)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to "Log in", new_user_session_path  %>
<%= link_to "LOg_out", destroy_user_session_path, method: :delete %>
<% if user_signed_in? %>
<% if current_user.userparam.nil? %>
<%= link_to "Profile", new_userparam_path %>
<% else %>
<%= link_to "Profile", userparam_path(current_user.id) %>
<% end %>

<%= link_to "Create new post", new_post_path %>
<% if @posts == [] %>
	<p>Create new post</p>
	<% else %>
		<% @posts.each do |post|%>
		<p>User <%= post.user.email %> write: %>
		<b><%= post.title %></b><br />
		<%= post.body %></p>
		<p><%= link_to "Read More", post_path(post.id) %></p>
	<% end %>
<% end %>

app/views/posts/edit.html.erb
<%= form_for @post, url: post_path(@post.id) do |f| %>

<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= f.text_field :title%><br>
<%= f.text_field :body%><br>
<%= f.submit "Create" %>
	
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path do |f| %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= f.text_field :nickname%><br>
<%= f.text_field :age%><br>
<%= f.submit "Create" %>

app/views/posts/show.html.erb
User: <%= @post.user.email %><br />
Nickname:<%= @post.nickname %><br />
Age: <%= @post.age %><br />
<% if @post.user_id == current_user.id %>

<%= link_to "Edit", edit_post_path(@post.id) %><br />

<%= link_to "Delete", post_path(@post.id), method: :delete %><br />

<% end %>